### ISSUE TITLE
The .jar file has a long reference of its binary

### ISSUE THREAD

**Issue by crashuniverse** [adamhooper/selenium-server-standalone-jar#11]
Currently .jar file has a relative reference of `./node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-3.4.0.jar`. This is long and can be optimised for current versions of node and npm.

Enhancement:  
The .jar file should declare its binary so that node_modules has a accessible reference in its .bin folder. This would need a [bin key as recommended by npm](https://docs.npmjs.com/files/package.json#bin) in `package.json` so that using symlinks the link to jar can be just `./node_modules/.bin/selenium-server-standalone-3.4.0` or `selenium-server-standalone-3.4.0`.

**Comment by adamhooper** [comment]
I heartily recommend that you fork this project and implement the change you suggest. (Better yet, start a new project -- this one's Git history is enormous.)

Why not here? Because I think it's a different idea. My idea is for a jarfile path in _JavaScript_. I find a _symlink_ approach a slippery slope. If there is to be one symlink to the jar, then why not make it four: add `./node_modules/.bin/selenium-server-standalone-3.4.jar`, `./node_modules/.bin/selenium-server-standalone-3.jar` and `./node_modules/.bin/selenium-server-standalone.jar`? ... and then after users relied on the wrong symlink and got unexpected behavior, I'd hope they'd learn that using the symlinks is a bad idea and they should just get the jarfile path from JavaScript.

It's totally a niche project. I don't use it any more. I barely maintain it, beyond incrementing version numbers. A fork would be a pleasant outcome.

**Comment by crashuniverse** [comment]
I totally respect your idea of keeping it useful and error prone over silly things. Thanks for the _why not here_ explanation. I see what you mean and I'd fork to make any use case specific changes. 

Thanks for this great idea and implementation, I stumbled upon it last week & got it working and am finding it very useful.
